apiVersion: v1
kind: Secret
metadata:
  name: radigo-audiobookshelf-api
  namespace: audiobookshelf
type: Opaque
stringData:
  api_key: ENC[AES256_GCM,data:JGebK/KiC4QIyv9e/fiafeQZbyQ8iohoqL5H1GF4Yl9bxqzMWeCv/jY5TFhN9hkP5AE1LhkZwsDHG7GT897uxZM4xDzYLf4mnZERFim+HIPtJDzl9fbzYXdmHxH+36cDwBcluw9WAjlcwbRp2Po4VoSnZYBKwRm2tz5nB58PwQpaH2hDpuGzezI8jeZo8grcDGjVArtKKMxED1odKz8Ivw7d6m1nECK1rfEZifRmu70DXFd7HU3oA4GWIrf/XawI2qlFUDtxoHS2zy8orBVUaZCjj67Z,iv:HaF6c0x9PHopaqdH1/N4Cgv3TxNGEWYzOlFOk1kiUwg=,tag:g2DI93Oa09jhSvY/3rVLTg==,type:str]
  library_id: ENC[AES256_GCM,data:SpKKh4b6NWCVdHxNmrGMZjnQDUvFPWbR3OhhXdmzJ6NHXXe7,iv:gLuq2nKuH5AJqHqzAdx+1+R7IxvY3V96mrLy2WZNkds=,tag:PFwQFupfOyPtDdxt8356iQ==,type:str]
  base_url: ENC[AES256_GCM,data:+Mo/W1GCJZHd/m7+O+g1DQf9kvk6GW20hsxPqmZilqlhaFnlT57H96q4pPIHtHHBVhEbh/L5,iv:Qv1US23zQSqI/92r0fI4W0RX6kuAwqdSxNP8xG7NcO0=,tag:eoUSTsqZnbPrm6C3E+OuRg==,type:str]
sops:
  age:
    - recipient: age1ey9qstwaadrajnmu3q2aqzazk57dywfkzf74gfp5qqmq9ph7yq9s5zpxaa
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoWHdQd0hSUzMwOUhZSE1i
        TjFMcktRWU5RYlljQnV0NlU2V2poMjNxVmlZCjVNK0tVdUx5T2lITzRuazdWWTky
        QU5CclU3S3ZLWU9RUzV2V2svM0FWSm8KLS0tIGlTUzdyTGc0VDZKY1pkM3Q3WXMv
        REg4VDVQdDc2TUtDVTRqcVdiNTBXRjQKPhu9cno7QKG5cAFzYlP3EnKUaliJNaMw
        8ozL6gxnFdZeZimUTSoPmlzwl6b0xgSSh/pi/hMdBhZDUwNQqxwjVw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-03T16:21:18Z"
  mac: ENC[AES256_GCM,data:H4s2I8s2dfAOxui+U7QPOOBHl66HWRFw/b/GpT6eK/tybm30OoJaba1OIBRCnXWgCf76QOnJef9w/4gzKf97StpRBKq/ebqCk4BsAfI/Z28Ysxn8YUVGNjA9HI63sieeplWoybzsS+71Ce5uDufJQkwLMCFp6zJUIty9vV3DZyI=,iv:VRSeszjljkTDDPolbIxs7FBiz/DFqEKth5WpdakFKO0=,tag:02KPOQZCVPDkzDm6gopwjQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
