apiVersion: v1
kind: Secret
metadata:
    name: grafana-cloud-credentials
    namespace: monitoring
type: Opaque
stringData:
    GRAFANA_CLOUD_PROMETHEUS_URL: ENC[AES256_GCM,data:lDTidWyK8zWIg4Bam6DzhPZOZPuAOEwV1YKzl/cz5KAdZe+XK/6WuukPttlbgCneaUy8GOYRGa8EQqBnrQ/hiPlL98dgWz85,iv:eVkVvcNn6lMJLmQHaPRlbX4dez5tXypo057WuBrAYvg=,tag:8Wpu6LrP/MVUSgQCHhMJew==,type:str]
    GRAFANA_CLOUD_LOKI_URL: ENC[AES256_GCM,data:GW+rP/YHzq8ZH5ABoFCgvWC0kAsrPZyb/IzCEs3m9Vldv+UxGMxTqOA7IEuoeR4y/DE=,iv:BX4BVqS6ipHcn/yXrwi8ciKt3+qy4d6gKB7HUioMF30=,tag:U9+m+RC/sHhzRzJ/sB8cIw==,type:str]
    GRAFANA_CLOUD_USER: ENC[AES256_GCM,data:3l06mWFhHw==,iv:p3s11kleV73XNUK0bXNUSe66SvazspBjPErPMm4PtdM=,tag:g2uv0TEeThndryrgu/6+wA==,type:str]
    GRAFANA_CLOUD_LOKI_USER: ENC[AES256_GCM,data:glxKjExnuA==,iv:ISl/vQL3IWtCP7L4uWfLNJ+4R1feOQuW1MDsg4v/1f8=,tag:qcSSrrCTmNgBryvzA8P/Qw==,type:str]
    GRAFANA_CLOUD_API_KEY: ENC[AES256_GCM,data:LdETNu9hWI6GFNrXHV/BP+4059F+VpHkbVvKQ4+Ap/62GbaV2fxszvqHy2XJA7b+63WG1Xk7VQpRzR6JDcncgeM9TJOEsDapWTqQLYVptvMp6W3+QBgUbgNV9igemMbnhNaA5mvGY+fV1mulgst0dT3zdTrb7wO8QEK1Sn9077UOdR8O+2R/vxk2KDhYiDShITHuO8G1YsVxZmcB78Cwug==,iv:HEbhpOfmA4b47yHr/rz+PWnS15Gv+CiEjUtbJqbRBwQ=,tag:AJobx/FsqMp4MyT7UEhpNw==,type:str]
sops:
    age:
        - recipient: age1ey9qstwaadrajnmu3q2aqzazk57dywfkzf74gfp5qqmq9ph7yq9s5zpxaa
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxTU5Cc3J5QmdLWU1idmVE
            T1U2NnUrL3VRVG9zbHRRRWIzOUNqTlFSRWdJCldVQTRvOUhiM3M4T1BJSFdIUWE2
            RGxvbitXZEJTZVlRb0d5WjVnU3gzN2sKLS0tIGJJM1piNksrQ2Z0YzJ3STM4azR6
            Y3Q4RUp4bmpjOENoVU1aVXpLNmpueTAKaf/3oA8Jsl0DfwVymqjn4uqFTBtvHQZ0
            x3k5dj9fMlrjeKow2MCGNY4qytsAQtOxO5/FYnsXhCIQTJOSGM/WsA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-03T07:50:14Z"
    mac: ENC[AES256_GCM,data:SyB0DtJB25xeEfxiXVOJbJZX+UJQvE5Ag8nHCn9PNIAtgA4/H6Dhlni9CgRf+iggvFo10ttrovZl2Gt9L2NlA+PgdBhzKzTnCG2ASMDhuc1ZwkVIzoNw7H+Ahiqpc1uhg4Zph7chM/fTVUJbzxFizcLSp/osoIBdrsZ/6xND6mk=,iv:TZLu6du6k4J2IP+ElDScYCKvvquSEdDnzX6BSd77z9c=,tag:j0fcuw3+jfNyscKFMO5DLQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
