apiVersion: v1
kind: Secret
metadata:
    name: grafana-cloud-credentials
    namespace: monitoring
type: Opaque
stringData:
    GRAFANA_CLOUD_PROMETHEUS_URL: ENC[AES256_GCM,data:2DTpwpaKh7ouWCS7xi3Vz1zt7SYGJxBu9to028ZnGMY+YPIRccQl3F6FSZKRQ4jDTH2tovC/c2YBiTR93gHUMBTKhW5PmKlt,iv:zIOU83ywPHD8DJg4m9Q8cnKorrvNIiyTbjrs3S4HJFo=,tag:cMSsNj9gvV8BuHILn40Fgw==,type:str]
    GRAFANA_CLOUD_LOKI_URL: ENC[AES256_GCM,data:bku4kpLJ3DemVNTkhwDT1g8zgHkZDR0Jwal7JRJmXX5UfokowF83SqG8zqfIrUecvS0=,iv:eZKyCEdQa1/itM1LgxNIQYpZ5ymZPV08nCIe2T0Byls=,tag:G8rrdvx+JCOy9TBLCILMOQ==,type:str]
    GRAFANA_CLOUD_USER: ENC[AES256_GCM,data:Kn1AKkrdfg==,iv:TUYErVO8PRMLfRnO83ks2QJcNfY14tnF2l3pzjNSGM0=,tag:OCFHz0fueITyqN/2bnuyMw==,type:str]
    GRAFANA_CLOUD_API_KEY: ENC[AES256_GCM,data:GhRzL+uYV+sUyFeaGVE/1TTIAu328rIXDEoBWjVj2lST38Pi3SO4v9NXb10WOnbmjnEGi97knY70B/Wf1IPK1FV6LYR9J3+1WlSZOB9ndxOY9LykZOg2FUNCX+nV8ks92OtXfAeGc4dsqtviu2Uhav5LJ6aH99QQ1YQhHWKXxFou6krBSkY3u2fDX55qXMcp4KcjpA9pwjRu3fgJxSkZ+Q==,iv:picrEzwEMuFKF9DaYBoBWeNZ/NYTi0C3QZCkVizPbNY=,tag:zFB76bVR7ohelo4hh1LMGA==,type:str]
sops:
    age:
        - recipient: age1ey9qstwaadrajnmu3q2aqzazk57dywfkzf74gfp5qqmq9ph7yq9s5zpxaa
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDRkNlRHh5WCtxU1p5MDFk
            NENKRE5IK3ZHWFBMWlkwSy8yOElKWUNYekJ3CnV2blEvSSt0dmdTSW9Jc0ZzamNF
            eTV2azhTRGE3SHRoUDc4My9QWDRRbVEKLS0tIEZZUDRNY25HV1FqWVBkKzdueUtl
            UFp3ZFJwMkdEdUQralMxeEgxSW9wZUUKpmJjJBGC9pHZNlncKy65fqu6BPQtt+aJ
            jEEDhwz+GlgYM36YvooRH7Vq649Qz0SfgOHHszdCLmZpVHTki/mkDA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-03T07:36:54Z"
    mac: ENC[AES256_GCM,data:dfNLvtMMJV0FD5y0PPneismFkqqMZE55iT8DzpAACmDy5Osj43xMFt0XjZQK/pXguXBX2cRUAS2Zf6I1jwoudCxjDDubaRCzlII8OwZCk3AlOqoSKWwzl5GBsP9SkYJNHm61m/zIG46NtntM5F1404sQGqMMngVIJ5DL3+MepHc=,iv:+fdtrE9KiVsvkrBGQGTEACxsEBAbB/nWp93KPfbzcsY=,tag:FTsGdxZbTRS/P1k5AMaPXg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
