apiVersion: v1
kind: Secret
metadata:
    name: k8up-backup
    namespace: audiobookshelf
type: Opaque
stringData:
    ACCESS_KEY_ID: ENC[AES256_GCM,data:mBkBdCDyoAdxjDPN/gQ3UVbHMDff0DW8EUz8vsYvJpk=,iv:jhZGHJ/7Pqtpxx9N+CZYpk/W0ch5ejAhMG9i7Rwl8b4=,tag:zmbdyLBMaym5OiWfy85TCQ==,type:str]
    SECRET_ACCESS_KEY: ENC[AES256_GCM,data:CNDQ1Iy+tukrwrjrbPFonLiGJrIt+Y8JmAlmGzvwG3YECNF4RqVOAllKwWt23VxbxTHMo0AzfYcGII1MbfhVxg==,iv:xUwGnGeiFDfRnkslBkqm4xHhvCByiT1LrotNPoI6h/0=,tag:C5SMjoJqlmebC4VBeHTAkA==,type:str]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:YoOYQF9qQbbxb0ATfKGyjmMlI8q70nS+O4t1009AathWocx4s1WmwX8rX4/ockDmGYSsM6qM4//XR0qdvEcHoA==,iv:MfvH6SpCUJI8taK8uWl9ViACNUSlHZYd8TEjahZvdSU=,tag:mLZphpyGT6FSPpXmfYOVsg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwSm1VSGk3U2RHcHpLcHBx
            MU5RSnNneGNubm9iVXEva0Z3cU9Ub1JkQ0NZCjVMdDFLQmZtMy9BVnpHc1VPOW1r
            VkRGKzlrcm9oOVd1UHNxZWpIek5YYU0KLS0tIE12QWZIbDJUMmxtd2VLQ2I3d2Nj
            eTBuRm5zcU5NRFBPR1d4cGRGNnYzekkKJXpsO1WhaxtmOPQ6i/T14BQD+QnE4GJV
            FdoZyZQgIc9YSjY4zAQ6dKtSfjrH5riBtRkHEGuus5byAN0KwvpqzA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ey9qstwaadrajnmu3q2aqzazk57dywfkzf74gfp5qqmq9ph7yq9s5zpxaa
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-23T07:03:47Z"
    mac: ENC[AES256_GCM,data:7sDYvB34L2ZmfHKYD7YZJadrsSWomALa/g2+iAPXR1rOjr5BC5GMuoS8Bm5iu7AL1OqmAsNUbtPqFYyzghUAeaEzDKWLSnL0s/PeoB/8YStmt9Wl2iozCIRS0GzdTm5vDCYNT4ry1uM4foBQkUVTEk3cZtxkBIzgmW/uetbAXgM=,iv:vT39QQuHcXpXiEanOYT8DS8Wv3kcOTTnmGFYK1P/F2M=,tag:VktPKeUX5zEaA2HJ0hpg5g==,type:str]
    version: 3.13.3
