apiVersion: v1
kind: Secret
metadata:
    name: longhorn-sops-demo
    namespace: longhorn-system
type: Opaque
stringData:
    demo: ENC[AES256_GCM,data:EOrDQZk=,iv:gW53o5UWgU2lS4kkSHKBqgBzHkkKv9uO3zz/23jWs9k=,tag:THce40a6LZbMTTHzM7cfzQ==,type:str]
sops:
    age:
        - recipient: age1ey9qstwaadrajnmu3q2aqzazk57dywfkzf74gfp5qqmq9ph7yq9s5zpxaa
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtRTJvTHpScFRGV2xsQ2x6
            ZVgrOEwzRm9IVVhhZU9kNUdvSDdvakZjWG1ZCkw1ZDkrT0Y5TndvU2IybUc2VjUz
            MGNVZ1JQMVZnNzd3VGIzSjVyOHd6L2MKLS0tIHJESitCMVQvd3pPbkxkVVg1eTVn
            eEdBUVdKMVFlQ3FlRE9Tb2JPVHZpaDQKaeQX4mXKCcJrTGbIaUMA8R3l6d/aBWjG
            p2+oHqTtwGIPSkiRaU46xuV1g6i0nXWFWo6bksVms1bhiUd2DO/jhA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-02T06:51:05Z"
    mac: ENC[AES256_GCM,data:Ojc/coGo81nfFbxMPrVqJ2WveId9SzDLabKT8hymlZjTmUibG6FwfTXNSdnMTfgD/rlL2pN7DD0toxCQtZ3lxqVHS/3+scLrj0McJFSDF/n4dSuJhYc1C284hgjogZkWKttHyDhtWg297wp97B1X3XAIpxFBDxl2F1rMp2GroEE=,iv:gau05ZFRYqrJF4BX/cO4dNKazjfCgw/fu/7XZQmrAiQ=,tag:ATGjmb1ZaYG6FpcTDjePFw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
