apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: vikunja
  namespace: flux-system
spec:
  interval: 1h0s
  url: oci://ghcr.io/go-vikunja/helm-chart/vikunja
  ref:
    semver: "1.0.0"
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
