apiVersion: v1
kind: Secret
metadata:
    name: k8up-backup
    namespace: vikunja
type: Opaque
stringData:
    ACCESS_KEY_ID: ENC[AES256_GCM,data:P2Ieg+5cM0ddwhhjg5ADXVTpS9DZgo+acRExRDN4BDA=,iv:TUVExlhMfGB9Nw6ZHpJRvD3/E8QLMZALy8bx+9Fa6d8=,tag:kiMxD8PjbS1mnFpqpcXP2w==,type:str]
    SECRET_ACCESS_KEY: ENC[AES256_GCM,data:LNlTVfb1PoQKbSgq+Kyv7BHucgcgzdQVkWf2FuQlbMZjA22rqUZWPLM4Ek0P6TygkMtAO7sCD/pgGGnYqoAEfg==,iv:TToTeO3pGKZc9VWT2nZ+W4lr44J/1BUpy9EgDbbogEM=,tag:eWp1gVrMOoC+Nx9t3Ky7jQ==,type:str]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:4NMVc/jixi19nUxcit/WdF29MxTaQ/cHv1/75MtTK7HTlHxyH57D3sityZw1LxNJ6rIx15QgsOSrBUWoWFJySA==,iv:pm+zaRknoagy4ZJKw60vUmyND2WdqGW5MfE967O/dSs=,tag:QnAioWTxBzEti3gEY2Z6IQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5WitkbEo2T082SXRIZTJW
            eWZDaFZvaGxobzU1L0NzelRUOWhHRkhCeFRvCkJHQ3hkQWZMM0h3QzhlTFRsQWJw
            dmp6RkVJak5PTUJCZjZxZWF6S0tNdlUKLS0tIGRKWU5Jd3pTUGROeHBiQUt0dE1L
            NXBzNGRZN0Y1bFljV3pjb2Y0MFZFeFEK4kgko856eN0WXufzcxdb/AKcXWXzPVNu
            CXRP5KWdE37fjbmYtnvOb/58swq8ATPRZLGNNSWTveIMCxhBeUFLSw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ey9qstwaadrajnmu3q2aqzazk57dywfkzf74gfp5qqmq9ph7yq9s5zpxaa
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-23T07:03:49Z"
    mac: ENC[AES256_GCM,data:JquVsLvNSu+SAkTeMOdSXRKOMGnsFr1MGp8AGXahWr1IWGFqs9TUeuC5UEn0RRZGFdPXhlmkQn0pjvXUI1lWJMjSAxZzAZj/1SZjlJVIyWVaAHZkwS/NzhBN1hmBYLFAUOhKMIwFCSXFmm9VMq5vhGT9g6QdNom84HXNFUE9L7c=,iv:F66i3ZzuTcSViX2FqXiSh416Gqlkj6Tz1VgH/x3kr+4=,tag:j3ivSJayrjYRwv+fmBA0KQ==,type:str]
    version: 3.13.3
