apiVersion: v1
kind: Secret
metadata:
    name: vikunja-db
    namespace: vikunja
type: Opaque
stringData:
    #ENC[AES256_GCM,data:QDoJf10oYs2Y325gPtoNf+dxqjEIXV1BTpMXfwwgzZuoz95A1l01UcEiE+E=,iv:aLk/ZK8Ckp/OtBkQUGvmbq99CMlnVeXfuf4X3o4E6NQ=,tag:jQLdzf47Zj0Gj52OBlQaLQ==,type:comment]
    #ENC[AES256_GCM,data:BnYf4NtWmcZckeIBRn15inwT2gr5XpHyU/rhdR+jw7mHEgyKZ5fJj+fRY63nsKV4QFvGIBxgqTkGe/J5,iv:Y2boBvWSDQ4T7/psASwJfhDmB0kZI2trlMsokBF+zZM=,tag:1EmzbU4b6f1jOdYyaYVyeA==,type:comment]
    VIKUNJA_DATABASE_HOST: ENC[AES256_GCM,data:xK68W5HvmrGN1eQZ59JiVA44u+m4iaRCf8z7qmqu0UqqPer9ATdnqVyxiyb0PA==,iv:lhBjCOEgAcYUo4qaQJ8SF43KE4gMhXSTdHl2h7iD3Co=,tag:w4oiv9Z916oqf6F1Rsdxsw==,type:str]
    VIKUNJA_DATABASE_PORT: ENC[AES256_GCM,data:PCfS3Q==,iv:eQwz69XO3vf8a2TRHiyFqSaLCgwyw0ddvC7RyUNaQow=,tag:hwdMwLNed/0TBXjrsfv7yw==,type:str]
    VIKUNJA_DATABASE_USER: ENC[AES256_GCM,data:O3Bnqr/jqA==,iv:iyRtvBCSBoVJXcU2q64RI/mVmbm9t/IM+jF1m/W8Kuk=,tag:LyPeqbD8PMx9kuAIzG9ADQ==,type:str]
    VIKUNJA_DATABASE_PASSWORD: ENC[AES256_GCM,data:yMj7RiG6WUijMQsm9v5c4gP4kveYs05c/RjJroTTECb/b47sFlSPVa52Ocs=,iv:84aOSWiK8Lr1Jy8feJNieUNoSazjBeVet+nnVyQwhtE=,tag:JzEaHAXtZTbVovxyRArIiA==,type:str]
    VIKUNJA_DATABASE_DATABASE: ENC[AES256_GCM,data:BnOZ9wIBDg==,iv:Bo+F852qgaBCsgz+5kolq5UAbY6E1wCsGM7/pWt9x8Y=,tag:Qyh6Fsq1R9BKnoeSsSEq+A==,type:str]
    VIKUNJA_DATABASE_TYPE: ENC[AES256_GCM,data:IhcxJ3B6VsM=,iv:3BBsvgTjNiYW5wF9yHYTc3h1qqkOGUpiH8m3G74iyUA=,tag:rfgL3EMrlQ5ljIOaMjHdJA==,type:str]
sops:
    age:
        - recipient: age1ey9qstwaadrajnmu3q2aqzazk57dywfkzf74gfp5qqmq9ph7yq9s5zpxaa
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhbjJGdkhkVmp3VC9GbWpX
            NmNOUHFhM3czbHJYblVUNTVsdWplYW9rU2pNCkY1RVlxbnB4eldoYWZWNzJXb3Rr
            WWp0U3N3ZnJrWnp6OThaekJLTkNRYlEKLS0tIFpvMHBZSTZXSUsyR1ZoSHgyc2sw
            STZXc00rTk0zbENqcnZ2UGdhYmRtWE0K571lYspi2LZCdZiQxXwYRybnv7Gq3aLY
            WSrtjgqWb6T5gDQYG3JN895uGLZIrqEMTKS5DuGt9eOakCCVL8I/8g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-10T06:30:27Z"
    mac: ENC[AES256_GCM,data:uEJML355zLG9EA/Mzcsv8yWiQGQG2f5mRCe6P4xUCGy2wyBxGhshdhwxbzYzw+7Ie+/kYm2iop64lHMrUjPHpxVThtj3yoP7UJvmHhgcoNBUjG53b44oSBhIu8SmOsGELAkUyhVq4lGN+xBVJ5Sgsd9i/3Tvgoo4fjv1C3SocAE=,iv:qE3HqFEAcyXxjAhNgXkmcJnCCeniWp14IiaMMSzM1KM=,tag:l1YhxakugGwgXeT44jV5cQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
