apiVersion: v1
kind: Secret
metadata:
    name: vikunja
    namespace: vikunja
type: Opaque
stringData:
    #ENC[AES256_GCM,data:q+cziaJ0XQV4gPh/WIOF1R2mXTZ4qnyoNIsOGkUAeIsjr9VAUn1+luWa1eNIa8HapO8=,iv:x0GsA06+K6bG9gX3+Tp311g7fZ4vlj2q8/er9utWmag=,tag:r0MEzHHSL+YWdafiSJjF8g==,type:comment]
    #ENC[AES256_GCM,data:k49pvbqqgYBAeagyb9s30OWy9ZPpLzC+fkTCUmoYRRSwG/NaFFurdxW7FgXJ8Nv3jmSClcZY+kyNf0dRjtXSgZ5FjXpwLL3C2w==,iv:yFpGQOfIiAgJjqgZQSb4Yf4M3phPmFL78z42R1qSTWg=,tag:lPdG/3vFPd5EUw/J/0zemA==,type:comment]
    #ENC[AES256_GCM,data:tR3ECcowa4PfCYbXdF5eYnEj8Tb16ui2dZT9WGHS4Dbr/Gl0Fnd0awMP06xbBpdDa/cZ2qjkq52ApPddwQ4fnmEUZB0qg9tC7A==,iv:hOzx8k+SrCzS2I1T6sEebnzmmsbax2aOmHMH0Ej8Pwc=,tag:RAsuSRglSmG1wnyZXyAGiQ==,type:comment]
    VIKUNJA_SERVICE_SECRET: ENC[AES256_GCM,data:r60sU/qghwd3numQEjNa1QZFOQQddSfZhu+MmBzCctiztQHrCGmx7TANG54=,iv:toV3Br+IVwrfEwlLZVH7PsO4AebrDb/+oJC1LGTviGg=,tag:3qRMRsTfM+UQI417TYDVdg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlRTJHTmZPQk9TaTA4SVRt
            MW45S210VjVHcjFQeEVhL3ZEMGlUZGU0L24wCmVJSWlWZ0FHd05Lck9xNlZqbS9x
            dGd4RGFJeDYxNnZoWDNPNkVTYndiZzAKLS0tIHNWWW1hVi9RRS9BenNvT3BNRUpG
            alFwdk81T2JDVGs2Q3VzelI0aVFCb0UKiQekfhSBciTPU3vqfI5wPNTXr3XuyTAj
            oHyMKLtmFUuKT9BgEmnqOAEjTA+fVpVPXKlhIDHqyj2gfn07JAVoig==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ey9qstwaadrajnmu3q2aqzazk57dywfkzf74gfp5qqmq9ph7yq9s5zpxaa
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-22T13:16:07Z"
    mac: ENC[AES256_GCM,data:QkOxy5yG0ZTvJIjR99KPI1FQTVGaql15+xTY/PCe5LRJfFsLTsIdfucoVCWrqAEYb+cJo9aZx5LEbEbNB8E2kUwnlwY/V49ZfEdg43ce8agoltWVdJED0bOyChVgVXrs7S1DPshh3Wkx5prJYgr1gmpb8QGrsgkzAcybmq9AJJo=,iv:dAx3naPp/w27yurnXocR/6KOhbMmWNJjK4wQwsJectg=,tag:dw+KDGSqYV90BMGkHziYJw==,type:str]
    version: 3.13.3
