apiVersion: v1
kind: Secret
metadata:
    name: vikunja
    namespace: vikunja
type: Opaque
stringData:
    #ENC[AES256_GCM,data:rsknk7Lf0t8OTZT8Rs0IWvG/y1xcEvs0stR0NzWdvbm79BWRZxM=,iv:NRpIe2u9i10lGgQuwu+bH6XZawU0Av+YRTBFWTpAVUY=,tag:yEVHyPH78jZyH91m9Bgrzw==,type:comment]
    VIKUNJA_SERVICE_JWTSECRET: ENC[AES256_GCM,data:4XFg2JGtUS1AqKUfyiHZjutceP1iShSXYtWKU21XapXbdhkjeYhfKRA2Fx0=,iv:TISL992DQpjzKY1GnJCOnKNG8r3jt69sUeaoXEaet+8=,tag:9o5A6cnhti+amPpwawnsnQ==,type:str]
sops:
    age:
        - recipient: age1ey9qstwaadrajnmu3q2aqzazk57dywfkzf74gfp5qqmq9ph7yq9s5zpxaa
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2NHpZMC9MZ3B6bFhVd3Jm
            cythcGFXbGpickFvY2ZIdEVmQ2pBcE8zckFRCm1hbE5TOFNwQ0ZnSjlZZUtvR08v
            cmFFZFNFUUJNMVR2Z2RVT242QlZiMkEKLS0tIGNvZXphR3FuenpCODQyenl1V0hX
            NXFvMVB2WlNjYTdDQXBkK1hRZ1lBVk0K5vDC3lvgXbkfUnZXiw/jTslneiFOTM8p
            DZm7qyAGD68YhfuL8gpAVmW2SR2UsYBjPI1cfDUXQPNHW75fT00pMQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-10T06:30:25Z"
    mac: ENC[AES256_GCM,data:yIGFG9915XHWqHgmQiPwwQWXpkVe6+NCvtlchRLamIpbQcV5Lb5RSLnLMxKw9DKAOzNITEfangvvfDS/vZATsH9j/nlAi2wTdJoPJ7fWw+dKgOXi/5quMq9+LF3yWVMGdSF5BHIYOPxe4hmn5FvcNEccmtRbEafd2fwkp5VQDV0=,iv:joAmqEBIvdnDnQqWtbtdThrgzdHEzn13b+PHEBFhetY=,tag:dq+ItNCdqvF75/jiTb1InQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
