apiVersion: v1
kind: Secret
metadata:
    name: longhorn-r2-credentials
    namespace: longhorn-system
type: Opaque
stringData:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:a3f2waAsrFNfvgW5oxSwK0U5OtBy4YbwVuLSyBE94eE=,iv:77uagRDvPwk1Sv/jsjb670OAzmOkCHW1i2UnXVcJwjo=,tag:7tf0X+xadEAZYaop3pR/eA==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:evaR+6Htv11dHPy25EaIMkvHPLtHx2s/laro6y1kprYTnwxI+m8rMVVwM3HuUHjVz5XNHU5pHeoB8PgEKOhyfw==,iv:UPCvkcplY5k8drc0RjdnwlvBjFQvm6R51VICMYRSKRs=,tag:ouy/fYXA+RaG2Ffki9mzXQ==,type:str]
    AWS_ENDPOINTS: ENC[AES256_GCM,data:gs9EdotyKrmKelpC0sh+NyhG/SQ2StVZY74a0E23eF/Z5F/CAEWV8B/hogEyu68/svCVuBS7zypbDx4deFo3vTc=,iv:asuWBYiJVm1yIOq3atEkZh6DINKLPvc+ryqov+P4aXk=,tag:touGkDYDD4jHuDg7ojzVZA==,type:str]
    AWS_REGION: ENC[AES256_GCM,data:wDgF1Q==,iv:du/dtd+ZrvqJU3khRNApQQhVF1jS4kcfON3QOXFERg8=,tag:TxDrHp30JALJblsYDnnY0A==,type:str]
sops:
    age:
        - recipient: age1ey9qstwaadrajnmu3q2aqzazk57dywfkzf74gfp5qqmq9ph7yq9s5zpxaa
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkS1hFNzZXdU1zQWRaL2Vq
            a2JnaWJjUGVUeEZ2QTRwcEFGWlc1L0F5S25NCmFmcXhPV2N5c05BK0ZIOUNocUlM
            eE8ySWhoZEorSXdEc3JiMWJOa00zaHcKLS0tIGJIOFdydFRCR3BqZlpzNldFcW9h
            eUFaeDIwUlQ3b0FFNGdDOHdaTUp1d1UKEmnoUk94VzLUPbDZ69jdDu5Iq6krVyd2
            f+xbehefG6gNxZMPZRChZyjpf9up519lAca/Pv2sNy30uFJ3iYx7sg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-02T07:39:04Z"
    mac: ENC[AES256_GCM,data:ctPldU9ibEWNesRnLEyeTCqur43MgAN2NLwoje00HSpvK+mNDbtjLCtbp5OMh/iBDT+G1iwmY8y89x2sNckdBZSUDwnu2TGvqedGvNXJ6GwLwOfjEGRZ5eICXZNV8lgWZl7RonxiA1j5T59L00/i4vekXtvrO4OpfGMx1UTE/GY=,iv:RClHiLbAJ2WzZkWZeuu11yt/SNktGCfD9Gp1ATWYT4c=,tag:AiqOJd37ySJrT2HoFaMETw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
