apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: paperless-data
  namespace: paperless-ngx
  annotations:
    recurring-job-selector.longhorn.io: '[{"name":"backup-daily","isGroup":false}]'
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: paperless-media
  namespace: paperless-ngx
  annotations:
    recurring-job-selector.longhorn.io: '[{"name":"backup-daily","isGroup":false}]'
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 20Gi
