apiVersion: v1
kind: Secret
metadata:
    name: paperless
    namespace: paperless-ngx
type: Opaque
stringData:
    PAPERLESS_SECRET_KEY: ENC[AES256_GCM,data:gDixP+p3j2pTTmvCBK/42XWBkb8J16YQk4pr7CERlclJlSAWU6717kCojAeh6AVxZQ7Bno/T+TZXO9jC/ZOB4Q==,iv:UgHPM38vkHlLf7FjyRLS5icMpUeNCaR8joSWibPe6Fc=,tag:GbVZ5MC+mNPim8yUoMeAlQ==,type:str]
    PAPERLESS_ADMIN_USER: ENC[AES256_GCM,data:/HSj+Dd7ug==,iv:ZKehEdcAED3JqI8Ks6tQdJcKhxkN7+BrQUyyZx33uVc=,tag:xsgZHFC2cI/q5Al8RRrfKw==,type:str]
    PAPERLESS_ADMIN_PASSWORD: ENC[AES256_GCM,data:uIlRQZdmVl+XbzoFiyS03VS2,iv:24AQHsvaUZFQYj408fc1r+UWB2+5rKKVnvu2F2sDzSg=,tag:+5FlcF9kv7rVQFubFtEBbA==,type:str]
    PAPERLESS_URL: ENC[AES256_GCM,data:aID1bFukyeyrQG9ftGqU+wje72zICA95KOgQb7A9EUCQK/M=,iv:U8SlkciHOoT8QBvNgZB5b8Xp6w1EG80O7zxn3pK7Y8s=,tag:YWCRrfLhex0ZlGC9x5CbHA==,type:str]
sops:
    age:
        - recipient: age1ey9qstwaadrajnmu3q2aqzazk57dywfkzf74gfp5qqmq9ph7yq9s5zpxaa
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoYTlzanNRZU9qbXErM0Y2
            Ym1OWWdpQ3VrSDlkb2xycnU1MGFIN0lxWG1jClNDd3BieVVwcUIwVktLcEV6cnQ1
            R3J0T3IrSWV3RWgvc3laUnNuZGNyaTQKLS0tIFBkcVJPaVpMU3pCT29oLy9zVnVD
            Nm9MZWdjenBBWHYyRktnd0ltaTZETXMKH/wWdrUFc63am0G619XsAquUYG0yf9XX
            sFFlWRgc4W3WFHxqJF7kqFT1WNMNGwhzRwS1oCduDvNISmHRTt79kA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-10T12:30:16Z"
    mac: ENC[AES256_GCM,data:Z4GeqDvnCeV18nNGp8G5x3y4Njv2oZXIHV3q9KeBKCSCvEaYANqxJ1NY0Ny0SRnGpBkLrnJHjTRKtaBdHwm+2l2sfOVTBTE5eTQdsBfF8KDbMM93j5IwfUx325dGlV9rubeTxtUcHO5UY3geF2Jc/i1ot97+9NcUlHzL/OUPJ/A=,iv:Gh6wZ1Kr0zsT7MjiNWwukzJYLSVqRr8LarIldmHj5EU=,tag:B+lk0r+G5/4WOid47lfxyQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
