apiVersion: v1
kind: Secret
metadata:
    name: k8up-backup
    namespace: paperless-ngx
type: Opaque
stringData:
    ACCESS_KEY_ID: ENC[AES256_GCM,data:r2x1XP2kDfa14al0lhB1XcaCIJlwi142pnuCtMJZghk=,iv:cWzcoMTsMhpbkbKec26zlnb5Q9flbFuGjCmhBE4WFKQ=,tag:DaEvJyUoe13FkNx4xCQ6+g==,type:str]
    SECRET_ACCESS_KEY: ENC[AES256_GCM,data:jvOBIa1VVoq6k/jzabUGGuctOJZSJb11WOtzQEU2RiasRdfkGhqqXkxEfQHyzV9hqSNbMtQTp/eo8OolCmvuQw==,iv:FL7bOlFHmzI1X9gm8qd0WL2NszUvJodycgHGD9l7OXE=,tag:ZwIqSi7qlJ0uXFETdl0eGg==,type:str]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:vc47HyFsOaSXcRB7ETXoTvbSaxsGNkiw4BxW6GHSgtrhwpTXt0Bbjt0jk03uM6QA1oF29Ei6ssgFsFK/I+TE+w==,iv:YRcvL9EmV+PYBhSQTO6B9gtHn4hUs58uZ36qrZgEJdc=,tag:RvuI8ANxElRHG8k0xV7trg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5MzBpKzlXWGVYbVVnSXVG
            Vi90by9VQXJTMDkxd2h4aEhUb1BiVko3S0FNCjVRcjlxZkZpeldhVFJ3MlZKazgw
            Sm1UVGRUdTArUFFLNjNaNHcvbzh1Yk0KLS0tIFdicjcyY0RxUERZZytLNUJKbGNW
            bDRlZDBReW9HbVVJYUFMU0VtRkhuRU0Ki5gaZhqEgKJShE52HwKq/O/AIekQIzxE
            tPJsSZ2wqwryjl6ZyN6E7HyMA53UdnVl9ac5pbcCdPLUGzgmnowWRQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ey9qstwaadrajnmu3q2aqzazk57dywfkzf74gfp5qqmq9ph7yq9s5zpxaa
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-23T07:03:48Z"
    mac: ENC[AES256_GCM,data:/ej6axkeXe+YZG+9C93wWMvVohPshBz0qhiiTSoKj4l6I4iK9yxsnCCUEd2qI2YOXvFjm6G5jwd4h2+PjwrB2IRlWl4RWg5DG2J7cHN/nRbsG5wmhgnRS9kFMSILX8CcdEoEYv1hLcE93OuUllAtstAP4xYW88FgmvZzce2v4Vc=,iv:+SUXs7Tn39IAA5Pr33mV7YBTT5Gu8bzS5nX0YpWvM+Y=,tag:MGwMm8v5L5gLJBkVZcqUwA==,type:str]
    version: 3.13.3
