apiVersion: v1
kind: Secret
metadata:
    name: paperless
    namespace: paperless-ngx
type: Opaque
stringData:
    PAPERLESS_SECRET_KEY: ENC[AES256_GCM,data:IEWvfPCCydKcRvMc+T48zHUzjFXWOeh9MEvMxDW9k8hGQMlfwKHN7t0drSqZ1Z9O8aUp0QULjYQLucGguX5PoA==,iv:x7vBxvDoh+Qqsi4qX86Tb33B3UkmTBZ6uPiasFySrmo=,tag:GJt3jufp8LlZ15SO+OGK0Q==,type:str]
    PAPERLESS_ADMIN_USER: ENC[AES256_GCM,data:xqtkq6R66Q==,iv:DDMfN5d8kpMlSVf+4RW4/bGlB00vRpjuupvKNqX5ERg=,tag:TZkG02h2HsMWTRwUCmL4Lw==,type:str]
    PAPERLESS_ADMIN_PASSWORD: ENC[AES256_GCM,data:6JRKwUMWkCxwdrrvvGUHST/J,iv:Re0vaq/21HARslVx5WbWRTKz19GGu0Lz/9/4+1Sgwdk=,tag:ttLx2nWipr76PvU97b+jfQ==,type:str]
sops:
    age:
        - recipient: age1ey9qstwaadrajnmu3q2aqzazk57dywfkzf74gfp5qqmq9ph7yq9s5zpxaa
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIZ0tyK2VvUkxyQit3bTMw
            SWluTDEyVk9EaVFPaWpDS1FaUTVCQ1lORnhrCkVMTzR0eENZNEtmQTFVQ216RDJ6
            M3k3YndNZ3IwL2xoOTh6M0grb0lvNzgKLS0tIFVqRmlVWDkwR2FOSmVFUklISHFo
            SE10NHNDd21DU3hiblpyUjlxb2w1dzQKoNEz6uTEViTCfgDMQsuo5N2JjUWKJNkm
            2YaVxRR2+xkfGkhIALuL/r68YaQaFaxbVM/xwKKGdg7p4A6IJruFBQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-02T15:07:42Z"
    mac: ENC[AES256_GCM,data:HGus0cIhA1JXd6kAg5F5KF1uUmVOCrXeAUfLBi3kQXemzbyRt6tYVwD4Rrmq1+wcmMUohnGbJF9uvzYDTdmXDvweTNhfPKZUtU9T9K2C0Bvx0PHXv2OHivufZa5oXT0L83e/xethGlZvZfUIffcT0FooNAxPsW4MOUHZd2l7lZs=,iv:tVtYWn20AAKj8erV/l5xCxGs27IlDMHjbIAM3M/rfYs=,tag:DFuwa+W13xezPjQzD7DvWA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
