apiVersion: v1
kind: Secret
metadata:
    name: paperless-db
    namespace: paperless-ngx
type: Opaque
stringData:
    PAPERLESS_DBHOST: ENC[AES256_GCM,data:I+ZA16rOWn9KtXvn425cM/OWYZ2AEd4kazZM0y5rYlc=,iv:qxQnCPDP9eO/seLWdoa4tlVNYovReJU0ahQObQcyKEs=,tag:en1qV+/e/KV/28sCEJJ6xg==,type:str]
    PAPERLESS_DBPORT: ENC[AES256_GCM,data:kiaJ7A==,iv:NZCu7NVsSNPEJEtpr+Nlj2zIc7NvShHaVJCj1RjRteI=,tag:2UdclEjOI8vbI+OS4TzY7w==,type:str]
    PAPERLESS_DBUSER: ENC[AES256_GCM,data:4/EaZOVd1MaS,iv:5kRyOu1ovQa1M3m0PzHrfFAMj3ZOHRFSzwgSQ5VEdH0=,tag:vNtVekGlA6QX5HlVlB/3SQ==,type:str]
    PAPERLESS_DBPASS: ENC[AES256_GCM,data:y0aUnkBRMNsluu/+KSoy6ydUKxkkj2ioMeWKy3O6HUoREC86NjYakN1zajg=,iv:f4Bl0lA2Jqgn/BFhHFpIdkr2j3abmYziF5u5ROLa08A=,tag:5lBF5Y7D1SG6JDaoz4p+5A==,type:str]
    PAPERLESS_DBNAME: ENC[AES256_GCM,data:tBmt66uWtHwh,iv:C/ufEM9+fWXRn/r4iVODgb91OJ2JFkaLxUd1B7p0n6w=,tag:47KwxYQnLtBvJwk8SbJmdg==,type:str]
sops:
    age:
        - recipient: age1ey9qstwaadrajnmu3q2aqzazk57dywfkzf74gfp5qqmq9ph7yq9s5zpxaa
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3dFNNaHkrL0lDZGQ5eVEx
            NmpLRkRVR2dHb09ySXh6aW5xM1lQb0xhTUM0CkxVcHNvZFphWnJLRURHOXc3VUdy
            aUlUZWk4aEQxQ0VNRGxINE9rQW4zVkEKLS0tIE5obHZLU3owd0JqOVQ2MWlycE8x
            eUQydmhlcUZzUEFjQmRrUG9wZGMvNkkKg1qw2hondvhX7m98/Muu/NdG63vSVMha
            Eu/Ew/3w5IfqxeBXfOHgsldQeZvNmYPWhvqUry7MK6wIi3KcnYf0fw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-02T15:07:42Z"
    mac: ENC[AES256_GCM,data:YjxK8X5Xn0AQq9xYfhPodXRmWyFzBQEgYWA9xdTnxOCieeTQkjJsrvwpCCItfNunriCdxVJ7RfVfjpgui2g2+qGt8u5R1xgC4SD5jgG2Wz6Z4RxvyCSEqAW/28+F4UalynUe721iFJXjCyNsaqlcaVGYFOM3Ew0oLIwbZ3+xYI8=,iv:HKx4FHRsvXF2qWi6/KGpg26Eth2/wrcL2gzFR7tu6e4=,tag:arMszNaShrXorb1Q5PsaGg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
