apiVersion: v1
kind: Secret
metadata:
    name: k8up-backup
    namespace: home-assistant
type: Opaque
stringData:
    ACCESS_KEY_ID: ENC[AES256_GCM,data:MxFsFSitfh7MUUAwQ0uYiAu3bMijEEy9sc7oXZbsiqA=,iv:uN/sYaslQfytJhFFTKOE35eKXGu7DFmKU+JJpUtBYxo=,tag:fIHCdUFpwQbLnQWfcSDqyw==,type:str]
    SECRET_ACCESS_KEY: ENC[AES256_GCM,data:/uQdzoDVuChymSEUNqJJjo4kQaMATyaHXCuIAEoVKFwqSxjD5FjDVtL47N2Uvoac3kI/OSUpzeYtUaXy68XdlA==,iv:joQ2MmvoWWUEImnIxX/2ZlpFivLLntsdsiUoKKiG9qo=,tag:0uP+I/kW42V3urkuH93pew==,type:str]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:K5zir0aGxAvepwtbMMr7vDVsFSTB5L2Jk9ok4RzLbICkI6pHgsuGvesh9IeapNeCekQ/tbZ/iG8O7Drgp1+m2Q==,iv:4rUXgtVbq09wtx3Y49FerBqy6rd+XKCQHwXPEOntNZU=,tag:zfXllYoBWpW4Bh56a2eU4w==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1Zi9tY3czS3N4WG9zeWxL
            d01YMGRqNm1sQ3ROaE9pN2VnMWRycE5XK21FCkxlZUJsUmFwREw1N0pVQjcwRGts
            TlUyeExyQWdvYUNqSXRDbnNqb2RSUHcKLS0tIFRYRDhXeEphUVViMjR6NTZSZVdY
            VklXVDYxaEYzQUY0Z0Z0RVhlVFdsOFkKdS/FKW2Ps4jor5b4ZVkT2bHGWUxIeQU5
            7BnKofzBKqsO+WyYAZK9awhzYWfGmdVlgfNQ2BcCVewyeT36grE3uw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ey9qstwaadrajnmu3q2aqzazk57dywfkzf74gfp5qqmq9ph7yq9s5zpxaa
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-23T07:03:47Z"
    mac: ENC[AES256_GCM,data:Yqvbpwr8FDhAfHekOXkwQWW1PWHWvGY6olc5POb4TSkDsSmQAJXx0fQPunbJnafORnZr701EmEPNDwlpPsz7jPDN9IST/kJ8NORDEvMvRd1mSCYj8eplvHgZb1WsFEPwt3/A/iWbRT/KtesnNs8aE2XAWmlVTube9L5Oh0TVFOI=,iv:afyuFlc5b7gp2viT3ob0q6MpRwXpXVXiewAuwAY+3Ys=,tag:z44fiKHxVUcbod6KriMgWg==,type:str]
    version: 3.13.3
