apiVersion: v1
kind: Secret
metadata:
    name: home-assistant-db-url
    namespace: home-assistant
type: Opaque
stringData:
    #ENC[AES256_GCM,data:mc/YZmA7DCNZUtSr0Bc9OQIm3TX/cuVaf1we7lVZL89ac3XqWHZapoGWagGQNOmH82x0Qg==,iv:hIGXFsCS6UyPXL8/NZVlyjDTUwj055S+PFgi/wnP1J8=,tag:K69QYaGG9gMDsBMoWUSu/g==,type:comment]
    #ENC[AES256_GCM,data:PMAjtDDgAeXF/Rdge9uFvKX1WEeL5PiDAaRfCRziCNspMXGQk8QUC7jyK5cmBgdNR/mab6GQyjdzUaDL86y2idXpVPCuTuz7R/lGBc+keJOlYPDiLEkjXBbyTVUoz/yGI7YIG/0y,iv:7+/v0ipaFLRH/ssMMRuQ0U/y3QTK0cdfgF/WN530UzA=,tag:GldoKDOsbDIpf6dGpgd4yA==,type:comment]
    #ENC[AES256_GCM,data:XS//lNMOGyStfeDRAPjJF3wN4um7R+UXEGM5RAC1Qb5x6utErZ3vBGzRcPzGYQUwm+zPIk06AQGuvYpcupOSWN4kGU2YaXuWA8DfMadKADTkUIEP2cWIGD3yZaHEhMRh,iv:CvYWTsmtotXlFc+VVLhGtUZaThUB0AnuERhy8ywtZbM=,tag:IzFeCMeoflsBUVRdD8Q5cQ==,type:comment]
    DB_URL: ENC[AES256_GCM,data:nM+rnVnz/HZx0BNurHcaJqu7vAHO1OMAUI49RTEjjGRIn/fp9YMERlIJnmykDX8nQH6UvhJFTVVv5AgnSnOcgMVp2o4vXuSQ2qls+FXQWBO614JnllhvTi1r0mJeGtVTFgiP8qxbdJTcEOdYgPUUQv5EvWqMcziBtBpYcFc=,iv:qFcWGA3ZGxSoWtD0250XDN5nVtutXOPoLyKRXw4+ClU=,tag:2aEluSiYxWRDwkGvmQoENQ==,type:str]
sops:
    age:
        - recipient: age1ey9qstwaadrajnmu3q2aqzazk57dywfkzf74gfp5qqmq9ph7yq9s5zpxaa
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUNWFrSlJJR1BXbXVoZUd3
            ZzZRL0s1c3lrOUdxQUdDOHdxamR4bTZqSlRBCjl5OFZlWmc3cDQ2QXh2NVE2QTl4
            RUV3aEpLdlRzZnpjajQyWmhFRWR5czgKLS0tIC9SbEgzYi96OXROcml1UkpmMDlU
            RjFwUGtES1VYYTlBeFk1WmdnVW1EQW8KnVjDGhqjSk4JdmxFHPs3Btxj8Tp7l2AM
            PVC91buFTdYn7ql7a8DCVjlF0hHfmDhXA4Qo0losZ0IjzB6SeY+taQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-10T02:16:51Z"
    mac: ENC[AES256_GCM,data:rYyMzERaGqGzmIfawrpx0xj63ZMJDOgdcpi4h5Ru5ga/pARq/vuz2X1rysOkl84b3g/Rax7taRoc2xcwWrtV0ZAkyA0fo4IBJMYV6GnYFUPkV64oq63kNoQR1/Ot+BCdCNNFKMmi8/9cHL/MDyOA39ulstPHGTAXRLDHxOISO80=,iv:YStPhC/LZDcB/ubPg1vLTJFJgxSE7T+6dFVkZKqJC60=,tag:0ZHOvZhh+h6xnz4xIAYyeg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
