apiVersion: v1
kind: Secret
metadata:
    name: ghcr-secret
    namespace: audiobookshelf
type: kubernetes.io/dockerconfigjson
stringData:
    .dockerconfigjson: ENC[AES256_GCM,data:2sVY66ydAnGsWjM4zDJ12U96ZRCOrHaQx/yOUetGcL5mKR5Qe6ccwyaGkI7vuWskompW3mv9WAdUBWPPvRa/w4JYmQKkAzTGMuYBnhWtBjVPQ7gX5INWoET3xTXCYPZmREzdQvttqDeXSDqkhR8U,iv:AlmU1rgeMYz5QFMBMvIX5LitfTo+D+tLceaFabaFXzg=,tag:yULTlG4+bSUnJwUVhZYZXw==,type:str]
sops:
    age:
        - recipient: age1ey9qstwaadrajnmu3q2aqzazk57dywfkzf74gfp5qqmq9ph7yq9s5zpxaa
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6QW9peEdYMjRLQzBvbmJl
            bWNsM0xuaWplUWtoMFlxVldvTFhjUDJVbEZZClFPbDVzZktJc2JkeFdiemtzdG13
            bTRUTitUTVZVLytnY3dnSnJQbmRMRnMKLS0tIFpIQW52L1ZuSGtSRHpVUnZvZDE5
            RHhiRnVvN21zc1VPR0tRMnNjZlczMTAKOrCKC1xxDjXzSL5Hesbiv2SvMwcl6RYp
            5E9qEVynkOcGBmgU4b7WN94jOHZTdjuq4zr4GCRBLP8Rdri4kAO8iA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-04T04:23:15Z"
    mac: ENC[AES256_GCM,data:vf4fOifSBhqyV/eFOpS07+daDIexek0euH8LW5ZcLSY6RTSv2E2yb7UND46EWiCoiavBWqFIqzqVZ2xLOUde5w3aHOf3Mdgwh70xYFLxJt9bdkoNPLZHsFn6w9hV4CqBRAMpiVl20TAE3NF12ki3lMu2x3c7Av1wEtEKdKEA1lM=,iv:KSCuk9YT/G1lNhkXG1h05/inlHq5Rha4lJB54tQb5Pg=,tag:9TqB0ZqWPVdaSkfJMJmN7A==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
