apiVersion: v1
kind: Secret
metadata:
    name: ghcr-secret
    namespace: audiobookshelf
type: docker-registry
stringData:
    .dockerconfigjson: ENC[AES256_GCM,data:WieWDO6z8CvqszdRZPpxtybsStOTZKJiPXPQhZ5g/Z0g1QpNEWY9xMdf2LdPmB+q8DRWQX2Hk8AS4dkoCw0uVRv5EEDnSqWH//x/EsFFkPizJH+1WUD5eYb8XvUNqiGdxHvTBA+sojWQXkW5+fU4,iv:hab3jHBl280ZRHWhFHlprJcP04+4aKdOABtWWt3S8d8=,tag:2tzoEYhy+4GNLarJmsUmmQ==,type:str]
sops:
    age:
        - recipient: age1ey9qstwaadrajnmu3q2aqzazk57dywfkzf74gfp5qqmq9ph7yq9s5zpxaa
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSYnFzMU0zdUZHanhoQktC
            T3NHZW03MTNuRVk4ZHlxTTRkVXFxNVZGb21jCkpoaUsrNDNYOGdFR0h0cEcwSy93
            akgvODhNVVdrdlhtOGxFS2t1ZEluWEUKLS0tIEtXRldvR250aVl4aWlKVTh2bVpF
            dDFMQytrT1c4dnpyTFFKSVVlUTdPK0EKxU5I1u3V9qDvNNl8LyVu1wNUo/1pCRTq
            vT5NpDM1oZmQH1Gcte5cCnflxffrGjkmpTxU+Ejc3U83jqIrtzvo4Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-04T03:27:21Z"
    mac: ENC[AES256_GCM,data:Lj71ljIqwXHWN27sTGLFijNH1d+jCTiDSRb6r1zG1dFSEfbhpPqnT4yBRgFtuEekLUWgK9IhK+ouSEtGRlsS7N01Lvglgnx0/ckzh6T02zZSijj3qwU+ql9apW1wZV+MV4I4f6wPmYbgN1dB5TbMGbwfNgxig2NqBpZhD2x+7FA=,iv:NDk97xkcS4KubtyzvT2DbyvGsCac+xVbJhggmIBXQuM=,tag:7yBpOKhdV1mjKZMZZlZ10w==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
