apiVersion: v1
kind: Secret
metadata:
    name: immich-db
    namespace: immich
type: Opaque
stringData:
    password: ENC[AES256_GCM,data:r1qhRSf7Dy0Gto3k3lbjE/3DjAxflypGmDym7FvB2rk=,iv:XNnoAHTIBsusykXvhsVUxd7er/p9R3isvK8f3fhtxIw=,tag:GdKmWiS1sNudWFUUqSkORw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjM2J3enQvNXpLU21VVGJ4
            a0JTMkV1OGlUSStEMDFzRW9xYnQwNGFtMXpRCjczcWYyMnV6ZSs2VC9NVTd2WXNT
            aWoxR2xoQlljdW94MnpVQmMxR1VVTmsKLS0tIGJ1RDdvS1BYajVXdXE1Sy8wUUY0
            dXBLTjJ3NUd3SXBzeW92N1YxR085bHMKnVJe16nSr7S8DRSNNz5TrJpwClP6q+9m
            vkpyEel5g7v7rHBRYq6XHIbAO3Yf7126/DGJW2LCdAWct1HipeAUEQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ey9qstwaadrajnmu3q2aqzazk57dywfkzf74gfp5qqmq9ph7yq9s5zpxaa
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-07T17:56:27Z"
    mac: ENC[AES256_GCM,data:5nbE6iOfbhuCGohy6bj7jcLA7ZX5UWRNNOMoP3burvxSMozb1R5a6frxlNrSNA/mHIQYNVPHCF8vR+41CWbVL3IKhvActQ/n1Eegn7XXTYgAtPTXtpK3ZKIY65PlKGtF4SgC75C35qxh7QQGJTKdVjWo9uJariAwR3ekGy5xiaU=,iv:tPx18tRF9lCZMMfK0MVMu8+GjcGkVVTH74Zf7N6gyFs=,tag:tNuLZV7q110V9ijyn2x2kg==,type:str]
    version: 3.13.2
