apiVersion: v1
kind: Namespace
metadata:
  name: tailscale
  labels:
    # Tailscale proxies require privileged mode for network capabilities
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/audit: privileged
    pod-security.kubernetes.io/warn: privileged
