apiVersion: v1
kind: Secret
metadata:
    name: tailscale-operator-oauth
    namespace: tailscale
type: Opaque
stringData:
    client_id: ENC[AES256_GCM,data:sUnsps55ywbxT3v2Oox/jBg=,iv:trV64WQRm6nThcN0NbafXw6DWmMxjsMWSMtjlF112r0=,tag:ZwKZl0+Pb5K3TbttLoaUeg==,type:str]
    client_secret: ENC[AES256_GCM,data:C6wEDeNuqkx1o2rBBreqx1RhBRb56304xYKIdM8Cyc5/4VjSIs2bQL9rNUYOzWLVRTEAfDPG1iwg/nEQgfmlow==,iv:3OMq3WyU2qW4AvaCouif5Ipt4uEhftKHg+mR0+EeCnc=,tag:sXf5cV4HlZwiwQFXDqrEGQ==,type:str]
sops:
    age:
        - recipient: age1ey9qstwaadrajnmu3q2aqzazk57dywfkzf74gfp5qqmq9ph7yq9s5zpxaa
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVUU5IMmx1NGFNc2RhMFJm
            VE1SUzM4QjVWRGRFMFZSZ3VscFhNUklnaUVFCnc3Y1kyaDZCTGgvZTV6aG1kSFRI
            eXhLd0cvNnJQSHcybU1ReTZpUWx2VkkKLS0tIFJBYnZOWVVwWXlhdjFiaG1JR1VY
            ZGZMZm93Z2h0NFF4aitkd2VLVTBhNWcKZ168dSY5gc04Tsd5OHI1jBKaKWfnUuQl
            9P1j+ZZ/I1ZdprkOlQMaYJFLlO+9jCHvGid9aXyQR1nI5mYX7BRQmw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-02T17:04:44Z"
    mac: ENC[AES256_GCM,data:wJYUn0QhlG0KoMmmNeUQlE5xOsnOlb+xWpR65kO8TFMJ5BHuCQnscUTig+GtlCSh0f2TacNY75+57zw0t6I0S7+AEe74gO514bs9sldT/7WBvwZuNbrOEGCVQbLIj668U2Zxo7b1BBj3QLR44fjfEL3P0T7bfKvkTXF9HC4PyV4=,iv:3kznDyui8szgn40vrPVdvyU1YVmI0coPFuBYLHF1seU=,tag:MLHo1XM6i1l/xOYKletACg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
