apiVersion: v1
kind: Secret
metadata:
    name: tailscale-operator-oauth
    namespace: tailscale
type: Opaque
stringData:
    client_id: ENC[AES256_GCM,data:146abg6hfOo5m/khENMoFF4=,iv:5PciLgzP2YrGnDEhxyIsiLIoBJn2MLx9yn0w+zegvgQ=,tag:GeAscgswfPCS0VUu+7xthA==,type:str]
    client_secret: ENC[AES256_GCM,data:Oe9tb/L9aPz1FF5TEHq40vUd39wXT4tG2O+IGwkpjQaDDtsy3/VT7he3lxSqPZ8tGqydp1385MIExVM+JJyqCg==,iv:Wo562FK9ocZM94ppwmv9oVzS6LH+UQeX90l7edOL0NI=,tag:gRNWkp178pjlnQgRW9w5jg==,type:str]
sops:
    age:
        - recipient: age1ey9qstwaadrajnmu3q2aqzazk57dywfkzf74gfp5qqmq9ph7yq9s5zpxaa
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3dXBSL0lMaDRjTW5NdUl3
            VEExYy9PWVVqR0pLbmwxZFgxRTRaZHFjdUNjCjMxU0YzRm13QTZWZTFqMWpHbkF0
            MU94TFVVM0JicUhHazBnU01RNlBxUU0KLS0tIERFb3lRcjNIbFB1VktxUVRtSzRJ
            cmtwWEtpSHgySTZQb3R2N0tTZEovT2sK+C5wlavHSP6KPHYhX54zYd9MNOzIukhU
            8G83W3vWBnscn+bUR6jYo7HbgnaN8U9uKoV5NuFJiRfHKnIK6aSBHQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-02T14:27:03Z"
    mac: ENC[AES256_GCM,data:Wsi7Gx2TT2a6n6MJ/6dsr9VNnH+RhWwwVQGHTPNSJYo/tRsM8Pn6TTTXLKaxJ9O7faFA7ZXQcUFz872eLQi+zZjDd8v7xbuTPW701w/jBzTzh/lvrYXE3kNEsjHe3lSKK6so6/Ni9r66EbpEfBV03PilxjbtAlXSJOtiKc37qEU=,iv:7ySqM9i9k4Zw8Arp9rqB/Mhpf6cdBYBzZL3Vp2FnBwA=,tag:j3mQRQ/c0qvE/NsohjYVlg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
