apiVersion: v1
kind: Secret
metadata:
    name: tailscale-operator-oauth
    namespace: tailscale
type: Opaque
stringData:
    client_id: ENC[AES256_GCM,data:GUw9xW4T1wYniWMg3FmB9hc=,iv:oR+82TiMEDjINN+UPGqhwXFC1HlHAWLpJVGphOGf8wA=,tag:zjRYVW36M6ARG2YFMssemA==,type:str]
    client_secret: ENC[AES256_GCM,data:cjl6qJcQdBtNEBs6+F0MrhT6Epi+ohJbh5sNAvuCqouWsBOvtRQiVAgcTRdAvpKA99mwwuOFOM9beEFn6eXI3w==,iv:CfiAgCbI1rRSG9SLmSLNw85mhyr3ppaXG2lKJfH69YQ=,tag:DUTmaQnr71X7EsdAAEfb7w==,type:str]
sops:
    age:
        - recipient: age1ey9qstwaadrajnmu3q2aqzazk57dywfkzf74gfp5qqmq9ph7yq9s5zpxaa
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQYzBpOUlRem9DRU8xWk00
            eGFkQXIrWGtOSjZlK0hDaU05dUpqdFhuMEZvCnhnUWZkZ1BxNVVUN1Z3MzVvM095
            b0N2d3pzS3l4dVI0bWZMNTNwUXYxb0UKLS0tIDk5VGlYTmw4LzgyZVdjUFNJQzVC
            V1hyTC9URjBva1hFK2Z2RndJMzRUSmsKGHXbI3iICrEuHq1vq5V+OFn0eodspclt
            XWrcQs78MzKlDKOGvlMaWNYgKwWZgr0mJNeeYu5M2OkQxcHYz1Cspg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-03T03:12:12Z"
    mac: ENC[AES256_GCM,data:po3ucLQNW3TX/8iOEYUO+nTdWHjjMantdDwLyVudUevSSeJ4He6OKZVQtXPLnG6mwSTD375d9MIBFZzG2E0u/6YYLyQfVX2PiGUvXtdYzRyhQSECPnkW49Q+eHYZclXUFpXNBOykvtK8CgWWmdQhnmrofG/bbSXOpOWwCF5+TPA=,iv:vHiAh90yf6l2X67tWa9wCiRTyX2CmG/xDOO4HEi3hfg=,tag:e18Oelz/HjlDnWwxaxyivQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
