apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
namePrefix: audrey-
labels:
  - pairs:
      program: audrey
    includeSelectors: true
patches:
  - path: job.yaml
