apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - cluster.yaml
  - scheduledbackup.yaml
  - secret-r2-credentials.sops.yaml
  - database-vikunja.yaml
  - secret-vikunja-db.sops.yaml
  - database-paperless.yaml
  - secret-paperless-db.sops.yaml
