apiVersion: v1
kind: Secret
metadata:
    name: postgres-r2-credentials
    namespace: postgres
type: Opaque
stringData:
    ACCESS_KEY_ID: ENC[AES256_GCM,data:7qst75mqeVmTX4a08ChkzX/cYSyTtJ8EiTSMyg+0GQk=,iv:5uNbPAYW3Cr2JFVCu5wx1w9tU+qqiOBUu1tCLElibsU=,tag:BF5Bm284XSH1mFI2RjRcfA==,type:str]
    ACCESS_SECRET_KEY: ENC[AES256_GCM,data:b9bbCfkV5Bw3XjQDrzoqArjwyiJzwnnj81IF70e21GKoKgiSGbX4/wKfRa4Mt8hQcqPnvlK+masXM9PRsV/Obw==,iv:ETyfRvcBOwR5EdhjjI7zVt6bekXD7W+dBiu5UlyU+5w=,tag:V0NZDOghG2Dqjvgx7tN1ww==,type:str]
sops:
    age:
        - recipient: age1ey9qstwaadrajnmu3q2aqzazk57dywfkzf74gfp5qqmq9ph7yq9s5zpxaa
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5Q01PTGFRNDRremZ1bVc1
            ZGVudzc3czFYV1pmcjlzVmNzamFacnVHRWdRCmVPTW8zRnJOK0NYUWZnZmp5WWxC
            RXRKUWZtcUhMRkl5SlhCSk9kWWNibFEKLS0tIElLODZIL0t3UmlrWEtybGloTlVE
            WVh0U0V0UVJadUpLNmdYNmFOTk80QkEKRb852F0UZUR2ShDhmnvW1hiUGQrW7B3v
            mW7W6GZjDqgMaYe31dJ2ipb26nn4rbCQLhRVnftZLOzbc2EWjSn2xA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-07T14:54:00Z"
    mac: ENC[AES256_GCM,data:7c+uzyZIlIv3DlUveHwXEYR2LyeYOz2IMwgAU5rNYn13fOPzUGg+TJgOR4OaUAD7nQX8h7szyZ7tMCt8SUms6Yhd4a/aYd6JbLf9psrn5x4S0qlfRdAC/y2A0sXGEvXHbLvdeAqfx1MAvk8vvv+ZlMmM9It/9NVQ/VX/7hcJG2Y=,iv:+iVmyToUhV54PC6OC5rc5EIlQW1+98atzALLifJnTuM=,tag:8KGF76JPzRgGEuete5A0Rg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
