apiVersion: v1
kind: Secret
metadata:
    name: postgres-r2-credentials
    namespace: postgres
type: Opaque
stringData:
    ACCESS_KEY_ID: ENC[AES256_GCM,data:eYOK9554rMgArd8vFaP/ncX+1C6L3q5Z1UTjoO6/SY8=,iv:6DH/cV+2uuSLGmGfBqg4qFxibVc6ecR6D8hVr0fQcKA=,tag:UoacPj5pRRzKZ66nRl4EFA==,type:str]
    ACCESS_SECRET_KEY: ENC[AES256_GCM,data:xGaW/qxp/25CH+lAMrh9Y5WT0ill6AZjnzDJoJ5kREM+V294yyTmeBT9QOhmck2x33h8pKnWImJ7RINLKlhdBg==,iv:TKJFcU8KgGBIn4e3jVNWGqRdpYbYFMFrSnLLcoOrsxc=,tag:cjISLwO1aAswy3S57iDJOA==,type:str]
sops:
    age:
        - recipient: age1ey9qstwaadrajnmu3q2aqzazk57dywfkzf74gfp5qqmq9ph7yq9s5zpxaa
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1Qnp5a2xHMHlFOS9oUmZI
            ZENwb0QrYWVhTFltRUg0VXo4NlBQQ1FYdEE0Ck0zUStLTU05QmR1SkhPaWxCNDE5
            WHFaZnViV09DRTFBeUplVldFRXpUSDgKLS0tIDUwdnByUmNTSjh2UUdJTnJBM294
            WDN4d0RPNWtPN3lCcmo2bHRjWjJoNHcKNx+cQJpbT38A7fAXgUKn1lyegceFoRUL
            yVIZHsi4NLm/Tt2oDWvHk07FbSJW2ruF3YxD+z+hAz058Wl+lXngHA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-08T05:30:28Z"
    mac: ENC[AES256_GCM,data:vHRkjnr5hIcUJSAuuwngceqtEjZYxQDkLjfHtcAsBK357Z3/9ojsc9nJn2QvyK0Yh763mzDVJc06/vlDpqixw2wikYYradGGMNDYpLhAsKEUsGyodDOszoyUS5o7O1BdJkJjOF+7JUvCxv27eXTRa3l3aFkVA0Af++3prsGMGgI=,iv:iVQP6lB6J5Xh+XmmUawxKSr7a2T2p3brhVxp2GizmOY=,tag:pHsGj0EJWSApGD1VE7oOog==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
