apiVersion: v1
kind: Secret
metadata:
    name: postgres-r2-credentials
    namespace: postgres
type: Opaque
stringData:
    ACCESS_KEY_ID: ENC[AES256_GCM,data:axdvWHljz49IkboYU0+Lq6a3RJ8fXeTdCrVzNtNWknA=,iv:1QPnIL+h4jh5yJJZD3/eoDuIod43qct1ad/VZqvkvmI=,tag:HSlMfJkoVvUIpm2wN2aoTw==,type:str]
    ACCESS_SECRET_KEY: ENC[AES256_GCM,data:YyWbY4GnygOeOMtuYC9Gd153cM6KCZmeRgiV6MBOAkdidzKJ5HF5mvw8ZwiyOw2KdGTrbD3gxE6Ia+IXdsumPw==,iv:czBhZIXUiXVx6LxIaIMJP51BM7MizX8JnhzJa1dep+g=,tag:G1Lu/LNasgpvBG8O9YjqnQ==,type:str]
    ENDPOINT_URL: ENC[AES256_GCM,data:uryvFnW4S8YWHvFVaoeWGRehtuRgbCAIjtB7HuNuNrsimrov+yXJ345lX9qgW/PthUSa1exmjYYUl3C20vxMRDg=,iv:TEV3uYG5itBF3n+pM5kH8hOrbbK/b7J9DZ5Yz3aWGjg=,tag:jxqnI/qNN0zf4s2+ufgqWg==,type:str]
sops:
    age:
        - recipient: age1ey9qstwaadrajnmu3q2aqzazk57dywfkzf74gfp5qqmq9ph7yq9s5zpxaa
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5M0VyUzlSUWNFeWx0NFAz
            dHRmVm9KYnJoaUVod2czZVgvWDVkUGFHUXcwCmMxMkJRcG1idGtMbGJ0RHRoUmFk
            dlVPeVl4Uld1dzNNM3BjRGpaclZ1QVkKLS0tIG1RWlpvU2dsTlJzY2FCaTQyRW55
            b1VkcTRXNXUwUU0rb1dnaWVYYURyZVkKryfWQpdBmHxl8jkxDic4JBHXzEUFrIjD
            SKrM0qFA5/pPDUiiLnOZOfSfFm6JcX29977yOyQUgoensA0tGx/dMg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-10T12:30:23Z"
    mac: ENC[AES256_GCM,data:Qe/wqdJq+dEgyxtFssawqT3+k7VbXGY3zk8kobkYa2T078fZPdzxcGFVluJNur0x0v2QDRSM2g2bTBptbI4LhKfF1JGm3rOSA57MmPDRpnMBcnRytoNg6tjUuJLeKXBd7V6R6C3eL0+xOSe6xkmNJZerNew0uGCy9UVnwjuixbM=,iv:uXSdtfq+Zad/tOXhFqfNQH6kIwkRrdvrurjxGuDLX+4=,tag:fnytX2Mm1x6aTOUtBuRmoQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
