apiVersion: v1
kind: Secret
metadata:
    name: postgres-paperless-user
    namespace: postgres
    labels:
        cnpg.io/reload: "true"
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:bYTZFq4WoZ8f,iv:e2qS47Q86QZcYm3jkHoneNjAlRgwJZWJQk1OinOm9vw=,tag:AxEmd27kCPa83X1g3XA5HQ==,type:str]
    password: ENC[AES256_GCM,data:ol58slC3wIFUfAbkJiU0WY4ttug455UnjjqW8sMcOm1/l34v8cnrJVDsVs0=,iv:6oetFqsB98TXma7gyQ/IPMrpymldcKwYegrOPmtaeZ8=,tag:zcLA2gYOfn1xHsNNQZGsKw==,type:str]
sops:
    age:
        - recipient: age1ey9qstwaadrajnmu3q2aqzazk57dywfkzf74gfp5qqmq9ph7yq9s5zpxaa
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDdTJHRlFFWmREVDl0SEZy
            c3pGUkR2WXFFZ0tERmp4dElpMWRKbnEyRkhJCkh5c3NpNmlmOXJFVFlrR3ArK2RT
            U3NwZkpDWEtwWXVaeW5tVmVLbjh0aFUKLS0tIG81bnp1bjNkMTQ3V1lTa3pjWE5J
            QkpyRXdjU0hWY0E3cEVXS0ttVXIrYmcKqn6Xw0+vsv7roFERu/6e4hYsYwTay1dS
            8BhKI8DyOBWDztZFYaSrVjFtNPHq/D/US25a/ZKdXNNw4s3mr+E6tw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-02T15:07:42Z"
    mac: ENC[AES256_GCM,data:PGygtLhLMeRumkd6vezCxyyoih2FCOQMlkTycsDI+34b7I09uyBzqFkER6omC3ZJLfRwEKyI4hZrK/TAAqjeS3zaX17jjkKEkTjMzl40ttDRM175sO+XSxs4Cy7orprIsbYIgWeWt/OmA/6mh5CZ4wfScmsNu9gOvLWsXFXibMM=,iv:q6BNMkAUNI/qVq4H1veMPS6uUEXnSEHT+1eymBJJ/5M=,tag:2kp9mByI7GbRvRF70EOwqw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
