apiVersion: v1
kind: Secret
metadata:
    name: postgres-vikunja-user
    namespace: postgres
    labels:
        cnpg.io/reload: "true"
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:JdhxqR8vfA==,iv:pGarSrCAfDWyVbgmCOc40fKKNPBYpZchzVtEa9Evvw8=,tag:FdckQZALLQDCb0HEMauQRA==,type:str]
    password: ENC[AES256_GCM,data:3u5G9TmK6GuL/8yM8XPkNFqo2gk4jsiKzU3sbBjE5A2mhsrDxKZ0u0HktlM=,iv:i/xMngexQpMzVeIOXcMlzyKj8RRP/zLvgCjpP0QJP2s=,tag:hEUgHjRfBejpGiHUIPtNMw==,type:str]
sops:
    age:
        - recipient: age1ey9qstwaadrajnmu3q2aqzazk57dywfkzf74gfp5qqmq9ph7yq9s5zpxaa
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyTERod3FobG9OZW03S3dO
            Qk12aEtJZ05KZG9jdjZ5VXZzS0ZjbnpzaVJ3CjJyZXZqNHVUY3hIbElib3dpdjhz
            VDdIYUs5RXhBK0pVSUN1VU02L1F3bVUKLS0tIFQwVGI1dXNOa1ZpRlRISG9qRkhz
            TDdLcVJCRHgvV2k0SExvSmtUYWNQN00KnVG02Wg10q4NXyFpmBoOdy6/akc/SPqK
            oZ+YEbIKkytkPwN3WDoCLEZHdC0WGK1/oDdI1C0w547yE4ye+Iv7GA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-10T06:30:23Z"
    mac: ENC[AES256_GCM,data:7QVRUbOE6jaZfm/ZfDAHq+yW2Sr9La6Rd0po8aZ4RHRrdqpsAr9TEMKPKsv/KdrhJ8HUHnH6EYE7pF4GIX4t10733b6rnSaKt8qS5yb/+po5QKR6vdJYr8xb8X/eFTPeixgizFlQ+eZAsNUJUBIbXTR9GmUa1COxkcPNl9MawPA=,iv:Hrn+0EDMHhdTorWTKMWtQzmkvonT50FXxv06Pi/2L0A=,tag:K/Pu4zjOXl9w55BpZozJBQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
