apiVersion: v1
kind: Secret
metadata:
    name: postgres-immich-user
    namespace: postgres
    labels:
        cnpg.io/reload: "true"
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:1lgPnXRu,iv:h6fvfsJ/T7ljVvv5kXKI3wEdXgVueLGoSuQ7swZO0Wg=,tag:CYBnMxSnvh3RKp6Hzz4QjA==,type:str]
    password: ENC[AES256_GCM,data:ekQRBUFqDkfkfdy4xN+uKqRgM+L4DSPA6qxrYWCW8y4=,iv:ESk49F4OcMfmWvPGbec1AyMujGEltNC4FoIhmbrIWQU=,tag:EselkO3Q1K6+Z1Rd3mqu9g==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrdWhoQzJmbkJRMjNLMy9T
            Q3dVZzVBOGNZa0p2RkEySE9WV3d1U0VTZ2t3Cis5b0xyUDhocm1zVW1NN1krc25i
            OCtLRWpiYktNZ2pwZVozb3BYYWVQZkkKLS0tIFNPR0tDRlBTbGZacjJUMVFoUnRv
            anlXNmkydGRDWUJFQkIweG9ma1JaL0EKPxxi313nidr2XYFx2iXp0Rany5IRTbAw
            NZ4BmCTK8X3hOI4m3MYHSsGpZYockKPAhDH7Oy6QwTGJiCU+AhH4UA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ey9qstwaadrajnmu3q2aqzazk57dywfkzf74gfp5qqmq9ph7yq9s5zpxaa
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-07T17:31:48Z"
    mac: ENC[AES256_GCM,data:cnN3BGXQ6PTv34NIpT4MKnAJwU7ZmtaGbCO4y7YFDklH6U9T7TcqgCiVqerAAJXE4L9ZJd6ZpBJnE0ClsOcmNC+93PN4MLc+waD6i9D4TgZFq2vbQJgpOkS2I+rvg23240s/lzlgeUa/ejx252SZtfD0J1LxoruI+lwPZQv5AD0=,iv:xEpb8U1YufFYp3wBnmINMh2XiS6qAVnHJD6VJrlYOC8=,tag:8mmKK3/ophF/u31UbT1Z3g==,type:str]
    version: 3.13.2
